version: "3.9"
services:
  flaskapp:
    build: .
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=bonjour
      - POSTGRES_PASSWORD=adieux
      - POSTGRES_DB=blabla

  
volumes: 
  postgres_data:
